context:
  name: zstd
  version: 1.5.2

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://github.com/facebook/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7c42d56fac126929a6a85dbc73ff1db2411d04f104fae9bdea51305663a83fd0

build:
  number: 0
  # run_exports:
    # pretty bad removal of symbols in every other micro release:
    #   https://abi-laboratory.pro/tracker/timeline/zstd/
    #  Working smoothly since 1.4.x
    # - '{{ pin_subpackage("zstd", max_pin="x.x") }}'

requirements:
  build:
    - '{{ compiler("c") }}'
    - '{{ compiler("cxx") }}'
    - sel(win): msinttypes
    - ninja
    - cmake
